### ISSUE TITLE
在obsidian 0.16.5上还是不生效

### ISSUE THREAD

**Issue by seanchen123** [Quorafind/Obsidian-Table-Generator#18]
在obsidian 0.16.5上还是不生效，无法创建表格

**Comment by Quorafind** [comment]
无法复现，我 0.16.5 且在沙箱中试用了。请 按一下 Ctrl+p 以后输入 调试，复制对应的信息回复，我看一下如何复现。

**Comment by Parbler** [comment]
> 
1.表格太小，无法调整。
2.在输入内容时，又变成了markdown形式..
2.如果能做到像joplin的表格插件那样就好了...
